const Menu=[
    {
      id: 1,
      image: "images/breakfast.jpeg",
      name: "Breakfast",
      category: "Breakfast",
      price: " 150/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 2,
      image: "images/cake.jpg",
      name: "cake",
      category: "Dinner",
      price: "250/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 3,
      image: "images/burger.jpg",
      name: "Burger",
      category: "Evening",
      price: "70/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 4,
      image: "images/dosa.jpeg",
      name: "Dosa",
      category: "Dinner",
      price: "120/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 5,
      image: "images/fish.jpg",
      name: "Fish",
      category: "Dinner",
      price: "300/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 6,
      image: "images/garlicbred.jpg",
      name: "Garlic Bread",
      category: "Lunch",
      price: "110/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 7,
      image: "images/khichadi.jpg",
      name: "khichdi",
      category: "Dinner",
      price: "150/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 8,
      image: "images/salad.jpg",
      name: "salad",
      category: "Breakfast",
      price: "99/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 9,
      image: "images/Noodle.jpeg",
      name: "Noodle",
      category: "Lunch",
      price: "120/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 10,
      image: "images/moito.jpg",
      name: "moito",
      category: "Dinner",
      price: "90/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 11,
      image: "images/samosa.jpeg",
      name: "Samosa",
      category: "Dinner",
      price: "80/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 12,
      image: "images/sweet.jpg",
      name: "sweet",
      category: "Dinner",
      price: "220/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 13,
      image: "images/breakfast.jpeg",
      name: "Breakfast",
      category: "Breakfast",
      price: " 150/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 14,
      image: "images/cake.jpg",
      name: "cake",
      category: "Dinner",
      price: "250/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 15,
      image: "images/burger.jpg",
      name: "Burger",
      category: "Evening",
      price: "70/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 16,
      image: "images/dosa.jpeg",
      name: "Dosa",
      category: "Dinner",
      price: "120/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 17,
      image: "images/fish.jpg",
      name: "Fish",
      category: "Dinner",
      price: "300/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 18,
      image: "images/garlicbred.jpg",
      name: "Garlic Bread",
      category: "Lunch",
      price: "110/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 19,
      image: "images/khichadi.jpg",
      name: "khichdi",
      category: "Dinner",
      price: "150/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 20,
      image: "images/salad.jpg",
      name: "salad",
      category: "breakfast",
      price: "99/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 21,
      image: "images/Noodle.jpeg",
      name: "Noodle",
      category: "Lunch",
      price: "120/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 22,
      image: "images/moito.jpg",
      name: "moito",
      category: "Dinner",
      price: "90/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 23,
      image: "images/samosa.jpeg",
      name: "Samosa",
      category: "Dinner",
      price: "80/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
    {
      id: 24,
      image: "images/sweet.jpg",
      name: "sweet",
      category: "Dinner",
      price: "220/-",
      discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    },
  ];
  
  export default Menu;
  